<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2ipne7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2ipne7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ2ipne7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ2ipne7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ2ipne7\appProdProjectContainer([
    'container.build_hash' => 'Z2ipne7',
    'container.build_id' => '3c0dd30a',
    'container.build_time' => 1591545150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2ipne7');
